### ISSUE TITLE
Base CSS framework to generate a useable layout

### ISSUE THREAD

**Issue by CommCody** [Nietecht/mille-feuille-opinions#10]
We need some base layout to make this site present better:

1. without having todo customization inside of the markdown files.
2. be able to modify style sheets with SASS
3. without to much javascript requirements
4. as much styling features as possible with standard html elements

**Comment by CommCody** [comment]
I used the following list: [Top 20 Bootstrap Alternative CSS Frameworks 2019](https://themefisher.com/bootstrap-alternative-frameworks/)

Then I went 'till the Bijou framework and selected those which were still under ~active development and came up with this ordered list:
1. [Materialize](https://materializecss.com/getting-started.html)
    `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">`
2. [Mustard UI](https://kylelogue.github.io/mustard-ui/index.html)
    `<link rel="stylesheet" href="https://unpkg.com/mustard-ui@latest/dist/css/mustard-ui.min.css">`
3. [UIkit](https://github.com/uikit/uikit)
    `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.4.2/dist/css/uikit.min.css">`
4. [Milligram](https://milligram.io/#getting-started)
    `<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">`
    `<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css">`
    `<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css">`
5. [Foundation](https://get.foundation/sites/docs/installation.html)
    `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css" integrity="sha256-ogmFxjqiTMnZhxCqVmcqTvjfe1Y/ec4WaRj/aQPvn+I=" crossorigin="anonymous">`
6. [Bulma](https://bulma.io/documentation/overview/start/)
    `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">`

**Comment by Nietecht** [comment]
I'm not a CSS expert, but I feel like I wouldn't want to bother too much with type annotations in markup files. There's no custom rendering to abstract components like in JSX, so CSS is gonna have to do the heavy lifting.
I've also been a fan of being able to customize style sheets with SASS.
Other than that, no strong preferences... look & feel requirements are pretty minimal for me.

**Comment by CommCody** [comment]
You can shoot shit down here 🤣
so: 
- No to milligram fails 2 and 3
- no to bulma fails 1

**Comment by CommCody** [comment]
Foundation seems to be pretty js oriented: [Starter template](https://get.foundation/sites/docs/installation.html#html-starter-template) and 
![image](https://user-images.githubusercontent.com/1333336/80207371-4c016980-862e-11ea-8e91-e64937d0df9d.png)
